### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by Annaraf** [Zenius2016/BoardAlfa#13]
i don't understand why it can't be loaded.  help me please?

![haskell-atom](https://cloud.githubusercontent.com/assets/13984391/9906572/ff7a04b6-5cb4-11e5-9429-3f5af38e6e0b.png)

**Comment by squest** [comment]
In a normal condition, haskell behaves wildly when you don't conform to the norm, which is to make your filename lower case and consists of more than 1 char....

Try changing A.hs to an.hs and let's see what happen. Since you dont give a clue about what the whole A.hs file, we cannot know the extend of your problem.

**Comment by Annaraf** [comment]
i've changed the name. finally, it works

thank you :)
